import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'am';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.submit': 'Submit',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.reset': 'Reset',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Information',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.refresh': 'Refresh',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.print': 'Print',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.clear': 'Clear',
    'common.select': 'Select',
    'common.all': 'All',
    'common.none': 'None',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.apply': 'Apply',
    'common.update': 'Update',
    'common.create': 'Create',
    'common.remove': 'Remove',
    'common.duplicate': 'Duplicate',
    'common.copy': 'Copy',
    'common.paste': 'Paste',
    'common.cut': 'Cut',
    'common.undo': 'Undo',
    'common.redo': 'Redo',
    'common.region': 'Region',
    'common.select_region': 'Select region',
    'common.role': 'Role',

    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.complaints': 'Complaints',
    'nav.new_complaint': 'New Complaint',
    'nav.complaint_list': 'Complaint List',
    'nav.search_complaints': 'Search Complaints',
    'nav.analytics': 'Analytics',
    'nav.reports': 'Reports',
    'nav.users': 'User Management',
    'nav.notifications': 'Notifications',
    'nav.settings': 'Settings',
    'nav.permissions': 'Permissions',
    'nav.logout': 'Logout',
    'nav.profile': 'Profile',
    'nav.help': 'Help',
    'nav.about': 'About',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome',
    'dashboard.overview': 'System Overview',
    'dashboard.total_complaints': 'Total Complaints',
    'dashboard.open_complaints': 'Open Complaints',
    'dashboard.resolved_complaints': 'Resolved Complaints',
    'dashboard.pending_complaints': 'Pending Complaints',
    'dashboard.recent_complaints': 'Recent Complaints',
    'dashboard.quick_actions': 'Quick Actions',
    'dashboard.performance_metrics': 'Performance Metrics',
    'dashboard.activity_feed': 'Activity Feed',
    'dashboard.system_status': 'System Status',
    'dashboard.online': 'Online',
    'dashboard.offline': 'Offline',
    'dashboard.last_updated': 'Last Updated',
    'dashboard.view_all': 'View All',
    'dashboard.no_data': 'No data available',

    // Status
    'status.open': 'Open',
    'status.in_progress': 'In Progress',
    'status.pending': 'Pending',
    'status.resolved': 'Resolved',
    'status.escalated': 'Escalated',
    'status.closed': 'Closed',
    'status.cancelled': 'Cancelled',
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.enabled': 'Enabled',
    'status.disabled': 'Disabled',

    // Priority
    'priority.low': 'Low',
    'priority.medium': 'Medium',
    'priority.high': 'High',
    'priority.critical': 'Critical',
    'priority.urgent': 'Urgent',

    // Ethiopian Electric Utility Complaint Types
    'complaint_type.pole-fall': 'Pole Fall (Emergency)',
    'complaint_type.wire-cut': 'Wire Cut/Broken',
    'complaint_type.wire-sag': 'Wire Sagging',
    'complaint_type.no-supply-total': 'No Supply - Total Area',
    'complaint_type.no-supply-partial': 'No Supply - Partial Area',
    'complaint_type.no-supply-single-house': 'No Supply - Single House',
    'complaint_type.transformer-issue': 'Transformer Problem',
    'complaint_type.breaker-problem': 'Circuit Breaker Problem',
    'complaint_type.over-voltage': 'Over Voltage',
    'complaint_type.under-voltage': 'Under Voltage',
    'complaint_type.voltage-fluctuation': 'Voltage Fluctuation',
    'complaint_type.prepaid-meter-issue': 'Prepaid Meter Issue',
    'complaint_type.postpaid-meter-malfunction': 'Postpaid Meter Malfunction',
    'complaint_type.meter-reading-issue': 'Meter Reading Problem',
    'complaint_type.billing-issue': 'Billing Issue',
    'complaint_type.new-connection-request': 'New Connection Request',
    'complaint_type.disconnection-request': 'Disconnection Request',
    'complaint_type.reconnection-request': 'Reconnection Request',
    'complaint_type.line-maintenance': 'Line Maintenance Required',
    'complaint_type.safety-concern': 'Safety Concern',
    'complaint_type.other': 'Other Issue',

    // Regions
    'region.addis_ababa': 'Addis Ababa',
    'region.addis ababa': 'Addis Ababa',
    'region.afar': 'Afar',
    'region.amhara': 'Amhara',
    'region.benishangul_gumuz': 'Benishangul-Gumuz',
    'region.benishangul-gumuz': 'Benishangul-Gumuz',
    'region.dire_dawa': 'Dire Dawa',
    'region.dire dawa': 'Dire Dawa',
    'region.gambela': 'Gambela',
    'region.harari': 'Harari',
    'region.oromia': 'Oromia',
    'region.sidama': 'Sidama',
    'region.snnpr': 'SNNPR',
    'region.snnp': 'SNNP',
    'region.somali': 'Somali',
    'region.tigray': 'Tigray',

    // Roles
    'role.admin': 'Administrator',
    'role.manager': 'Manager',
    'role.foreman': 'Foreman',
    'role.call_attendant': 'Call Attendant',
    'role.technician': 'Technician',
    'role.supervisor': 'Supervisor',
    'role.operator': 'Operator',

    // Login
    'login.title': 'Ethiopian Electric Utility',
    'login.subtitle': 'Complaint Management System',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.signin': 'Sign In',
    'login.signing_in': 'Signing In...',
    'login.demo_credentials': 'Demo Credentials:',
    'login.click_to_fill': 'Click on any credential to auto-fill the form',
    'login.success': 'Login Successful',
    'login.success_desc': 'Welcome to Ethiopian Electric Utility Complaint Management System',
    'login.error': 'Login Failed',
    'login.error_desc': 'Please check your email and password',
    'login.change_password': 'Change Password',
    'login.change_password_desc': 'Please contact your system administrator to change your password',

    // Complaint Form
    'complaint.new_complaint': 'New Complaint',
    'complaint.customer_name': 'Customer Name',
    'complaint.customer_phone': 'Customer Phone',
    'complaint.customer_email': 'Customer Email',
    'complaint.complaint_type': 'Complaint Type',
    'complaint.priority': 'Priority',
    'complaint.region': 'Region',
    'complaint.description': 'Description',
    'complaint.submit_complaint': 'Submit Complaint',
    'complaint.submitting': 'Submitting...',
    'complaint.complaint_id': 'Complaint ID',
    'complaint.date_created': 'Date Created',
    'complaint.last_updated': 'Last Updated',
    'complaint.assigned_to': 'Assigned To',
    'complaint.customer_info': 'Customer Information',
    'complaint.complaint_details': 'Complaint Details',
    'complaint.attachments': 'Attachments',
    'complaint.comments': 'Comments',
    'complaint.history': 'History',
    'complaint.resolution': 'Resolution',
    'complaint.feedback': 'Feedback',
    'complaint.rating': 'Rating',
    'complaint.follow_up': 'Follow Up',
    'complaint.escalate': 'Escalate',
    'complaint.reassign': 'Reassign',
    'complaint.close': 'Close Complaint',
    'complaint.reopen': 'Reopen',
    'complaint.duplicate': 'Mark as Duplicate',
    'complaint.merge': 'Merge Complaints',
    'complaint.print': 'Print Complaint',
    'complaint.export': 'Export Complaint',
    'complaint.share': 'Share Complaint',
    'complaint.success': 'Complaint Submitted Successfully',
    'complaint.created': 'has been created',
    'complaint.customer_address': 'Customer Address',
    'complaint.meter_number': 'Meter Number',
    'complaint.account_number': 'Account Number',
    'complaint.title': 'Complaint Title',
    'complaint.submit_new_complaint': 'Submit a new electrical supply complaint',
    'complaint.details': 'Complaint Details',
    'complaint.select_category': 'Select complaint category',
    'complaint.select_priority': 'Select priority level',
    'complaint.description_placeholder': 'Provide detailed description of the issue, including when it started, affected areas, and any relevant information...',
    'common.submitting': 'Submitting...',
    'complaint.updated': 'Complaint Updated',
    'complaint.update_success': 'The complaint has been successfully updated.',
    'complaint.update_failed': 'Failed to update complaint',
    'complaint.fill_required_fields': 'Please fill in all required fields',
    'complaint.submission_success': 'Complaint submitted successfully. Reference ID:',
    'complaint.submission_failed': 'Failed to submit complaint',
    'complaint.success_desc': 'Your complaint has been submitted successfully',
    'complaint.error': 'Submission Error',
    'complaint.error_desc': 'There was an error submitting your complaint',

    // Form Labels and Placeholders
    'form.customer_information': 'Customer Information',
    'form.complaint_details': 'Complaint Details',
    'form.enter_full_name': 'Enter full name',
    'form.email': 'Email',
    'form.phone_number': 'Phone Number',
    'form.address': 'Address',
    'form.complete_address': 'Complete address including sub-city/woreda',
    'form.select_region': 'Select region',
    'form.service_center': 'Service Center',
    'form.select_service_center': 'Select service center',
    'form.select_region_first': 'Select region first',
    'form.complaint_number': 'Complaint Number',
    'form.account_number': 'Account Number',
    'form.complaint_title': 'Complaint Title',
    'form.category': 'Category',
    'form.priority': 'Priority',
    'form.detailed_description': 'Detailed Description',
    'form.select_predefined_title': 'Select a predefined title or choose \'Custom\'',
    'form.custom_title': 'Custom Title (Type your own)',
    'form.enter_custom_title': 'Enter your custom complaint title',
    'form.brief_description': 'Brief description of the issue',
    'form.select_complaint_category': 'Select complaint category',
    'form.select_priority_level': 'Select priority level',
    'form.submit_complaint': 'Submit Complaint',
    'form.submitting': 'Submitting...',

    // Priority Labels
    'priority.emergency_response': 'Emergency Response',
    'priority.high_priority': 'High Priority',
    'priority.standard_priority': 'Standard Priority',
    'priority.low_priority': 'Low Priority',

    // Emergency Info
    'emergency.hotline': 'Emergency Hotline:',
    'emergency.phone': '+251-11-EMERGENCY',
    'utility.portal_name': 'Ethiopian Electric Utility Service Portal',

    // Customer Portal
    'customer_portal.title': 'Customer Portal',
    'customer_portal.account_validation': 'Account Validation',
    'customer_portal.enter_account_info': 'Enter Your Account Information',
    'customer_portal.account_info_desc': 'Please enter your Contract Account Number or Business Partner Number to access the complaint form.',
    'customer_portal.account_number_label': 'Contract Account / Business Partner Number',
    'customer_portal.account_number_placeholder': 'Enter your account number (e.g., 1000123456)',
    'customer_portal.account_number_help': 'You can find this number on your electricity bill or contract documents',
    'customer_portal.validate_account': 'Validate Account',
    'customer_portal.validating': 'Validating...',
    'customer_portal.validation_success': 'Account Validated',
    'customer_portal.account_found': 'Your account has been found and verified.',
    'customer_portal.validation_failed': 'Account Not Found',
    'customer_portal.validation_error': 'Validation Error',
    'customer_portal.validation_error_desc': 'Unable to validate account. Please try again.',
    'customer_portal.account_verified': 'Account Verified',
    'customer_portal.customer_name': 'Customer Name',
    'customer_portal.account_number': 'Account Number',
    'customer_portal.account_type': 'Account Type',

    // Complaint List
    'complaint_list.title': 'Complaint List',
    'complaint_list.all_complaints': 'All Complaints',
    'complaint_list.my_complaints': 'My Complaints',
    'complaint_list.assigned_complaints': 'Assigned Complaints',
    'complaint_list.unassigned': 'Unassigned',
    'complaint_list.overdue': 'Overdue',
    'complaint_list.recent': 'Recent',
    'complaint_list.filter_by': 'Filter By',
    'complaint_list.sort_by': 'Sort By',
    'complaint_list.date_range': 'Date Range',
    'complaint_list.from_date': 'From Date',
    'complaint_list.to_date': 'To Date',
    'complaint_list.results_found': 'results found',
    'complaint_list.no_complaints': 'No complaints found',
    'complaint_list.load_more': 'Load More',
    'complaint_list.refresh': 'Refresh List',
    'complaint_list.bulk_actions': 'Bulk Actions',
    'complaint_list.select_all': 'Select All',
    'complaint_list.selected_items': 'Selected Items',

    // Analytics & Reports
    'analytics.title': 'Analytics',
    'analytics.overview': 'Analytics Overview',
    'analytics.complaints_by_type': 'Complaints by Type',
    'analytics.complaints_by_region': 'Complaints by Region',
    'analytics.complaints_by_status': 'Complaints by Status',
    'analytics.complaints_by_priority': 'Complaints by Priority',
    'analytics.resolution_time': 'Average Resolution Time',
    'analytics.customer_satisfaction': 'Customer Satisfaction',
    'analytics.performance_metrics': 'Performance Metrics',
    'analytics.trends': 'Trends',
    'analytics.monthly_report': 'Monthly Report',
    'analytics.quarterly_report': 'Quarterly Report',
    'analytics.annual_report': 'Annual Report',
    'analytics.custom_report': 'Custom Report',
    'analytics.generate_report': 'Generate Report',
    'analytics.export_data': 'Export Data',
    'analytics.chart_type': 'Chart Type',
    'analytics.time_period': 'Time Period',
    'analytics.comparison': 'Comparison',

    // Reports
    'reports.title': 'Reports',
    'reports.complaint_summary': 'Complaint Summary',
    'reports.performance_report': 'Performance Report',
    'reports.user_activity': 'User Activity Report',
    'reports.system_usage': 'System Usage Report',
    'reports.customer_feedback': 'Customer Feedback Report',
    'reports.sla_compliance': 'SLA Compliance Report',
    'reports.regional_analysis': 'Regional Analysis',
    'reports.trend_analysis': 'Trend Analysis',
    'reports.executive_summary': 'Executive Summary',
    'reports.detailed_report': 'Detailed Report',
    'reports.schedule_report': 'Schedule Report',
    'reports.email_report': 'Email Report',
    'reports.report_settings': 'Report Settings',

    // User Management
    'users.title': 'User Management',
    'users.add_user': 'Add New User',
    'users.full_name': 'Full Name',
    'users.email_address': 'Email Address',
    'users.phone_number': 'Phone Number',
    'users.role': 'Role',
    'users.service_center': 'Service Center',
    'users.active': 'Active',
    'users.inactive': 'Inactive',
    'users.created': 'Created',

    // Settings
    'settings.title': 'System Settings',
    'settings.notifications': 'Notifications',
    'settings.security': 'Security & Access',
    'settings.system': 'System Configuration',
    'settings.language': 'Language',
    'settings.save_changes': 'Save Changes',
    'settings.company_info': 'Company Information',
    'settings.company_name': 'Company Name',
    'settings.support_email': 'Support Email',
    'settings.support_phone': 'Support Phone',
    'settings.website': 'Website',
    'settings.address': 'Address',
    'settings.timezone': 'Timezone',
    'settings.currency': 'Currency',
    'settings.system_language': 'System Language',
    'settings.language_preview': 'Current Language Preview',
    'settings.working_hours': 'Working Hours',
    'settings.start_time': 'Start Time',
    'settings.end_time': 'End Time',
    'settings.working_days': 'Working Days',

    // Permissions
    'permissions.access_denied': "You don't have permission to access this resource",

    // Dashboard Titles
    'dashboard.admin_title': 'System Administration Dashboard',
    'dashboard.manager_title': 'Regional Management Dashboard',
    'dashboard.foreman_title': 'Field Operations Dashboard',
    'dashboard.call_attendant_title': 'Customer Service Dashboard',
    'dashboard.technician_title': 'Technician Dashboard',

    // Role Display Names
    'role.admin_display': 'Administrator',
    'role.manager_display': 'Manager',
    'role.foreman_display': 'Foreman',
    'role.call_attendant_display': 'Call Attendant',
    'role.technician_display': 'Technician',

    // Search & Filter
    'search.title': 'Search Complaints',
    'search.subtitle': 'Find and filter complaints with advanced search capabilities',
    'search.placeholder': 'Search complaints by title, description, or ID...',
    'search.search_filter': 'Search & Filter',
    'search.filters': 'Filters',
    'search.export_results': 'Export Results',
    'search.grid_view': 'Grid View',
    'search.list_view': 'List View',
    'search.all_status': 'All Status',
    'search.all_priorities': 'All Priorities',
    'search.all_categories': 'All Categories',
    'search.all_regions': 'All Regions',
    'search.status': 'Status',
    'search.priority': 'Priority',
    'search.category': 'Category',
    'search.region': 'Region',

    // Customer Portal
    'customer.portal_title': 'Customer Service Portal',
    'customer.portal_subtitle': 'File complaints and track your service requests',
    'customer.search_title': 'Find Your Account',
    'customer.search_type': 'Search Type',
    'customer.contract_account': 'Contract Account',
    'customer.business_partner': 'Business Partner',
    'customer.contract_number': 'Contract Account Number',
    'customer.business_partner_number': 'Business Partner Number',
    'customer.enter_search_value': 'Please enter a search value',
    'customer.found': 'Customer Found',
    'customer.found_description': 'Customer information loaded successfully',
    'customer.search_failed': 'Customer not found. Please check your account number.',
    'customer.information': 'Customer Information',
    'customer.name': 'Customer Name',
    'customer.phone': 'Phone Number',
    'customer.email': 'Email Address',
    'customer.address': 'Address',
    'customer.meter_number': 'Meter Number',
    'customer.connection_type': 'Connection Type',
    'customer.file_complaint': 'File a Complaint',
    'customer.complaint_form': 'Complaint Form',
    'customer.complaint_title_placeholder': 'Brief description of the issue',
    'customer.complaint_description_placeholder': 'Please provide detailed information about the issue, including when it started, affected areas, and any relevant details...',
    'customer.urgency': 'Urgency Level',
    'customer.urgency.low': 'Low - Can wait',
    'customer.urgency.medium': 'Medium - Normal priority',
    'customer.urgency.high': 'High - Urgent attention needed',
    'customer.preferred_contact': 'Preferred Contact Method',
    'customer.contact.phone': 'Phone Call',
    'customer.contact.email': 'Email',
    'customer.contact.sms': 'SMS',
    'customer.additional_phone': 'Additional Phone (Optional)',
    'customer.additional_email': 'Additional Email (Optional)',
    'customer.complaint_notice': 'Your complaint will be reviewed and assigned to the appropriate team. You will receive updates via your preferred contact method.',
    'customer.status.active': 'Active',
    'customer.status.inactive': 'Inactive',
    'customer.status.suspended': 'Suspended',

    // Landing Page
    'landing.welcome_title': 'Welcome to Ethiopian Electric Utility',
    'landing.welcome_description': 'Your trusted partner for reliable electricity services across Ethiopia. File complaints, track service requests, and access customer support.',
    'landing.customer_portal': 'Customer Portal',
    'landing.customer_portal_description': 'File complaints and track your service requests online.',
    'landing.staff_portal': 'Staff Portal',
    'landing.staff_portal_description': 'Access the management system for EEU staff members.',
    'landing.access_customer_portal': 'Access Customer Portal',
    'landing.staff_login': 'Staff Login',
    'landing.contact_title': 'Need Help?',
    'landing.contact_description': 'Our customer service team is here to assist you.',
    'landing.contact.phone': 'Phone Support',
    'landing.contact.email': 'Email Support',
    'landing.contact.hours': 'Service Hours',
    'landing.contact.weekdays': 'Mon-Fri: 8:00 AM - 6:00 PM',
    'landing.contact.weekend': 'Sat: 9:00 AM - 1:00 PM',
    'landing.footer.rights': 'All rights reserved.',
    'landing.footer.version': 'Version',
    'landing.feature.file_complaints': 'File complaints online',
    'landing.feature.track_status': 'Track complaint status',
    'landing.feature.account_lookup': 'Account information lookup',
    'landing.feature.multilingual': 'Available in English & Amharic',
    'landing.feature.manage_complaints': 'Manage customer complaints',
    'landing.feature.analytics_reports': 'Analytics and reports',
    'landing.feature.user_management': 'User management',
    'landing.feature.role_permissions': 'Role-based permissions',
  },
  am: {
    // Common
    'common.save': 'አስቀምጥ',
    'common.cancel': 'ተወው',
    'common.submit': 'አስገባ',
    'common.edit': 'አርም',
    'common.delete': 'አጥፋ',
    'common.view': 'ተመልከት',
    'common.add': 'አክል',
    'common.search': 'ፈልግ',
    'common.filter': 'ማጣሪያ',
    'common.reset': 'እንደ ነበር መልስ',
    'common.loading': 'በመጫን ላይ...',
    'common.error': 'ስህተት',
    'common.success': 'ተሳክቷል',
    'common.warning': 'ማስጠንቀቂያ',
    'common.info': 'መረጃ',
    'common.close': 'ዝጋ',
    'common.confirm': 'አረጋግጥ',
    'common.back': 'ተመለስ',
    'common.next': 'ቀጣይ',
    'common.previous': 'ቀዳሚ',
    'common.refresh': 'አድስ',
    'common.export': 'ወደ ውጭ ላክ',
    'common.import': 'ከውጭ አምጣ',
    'common.print': 'አትም',
    'common.download': 'አውርድ',
    'common.upload': 'አስገባ',
    'common.clear': 'አጽዳ',
    'common.select': 'ምረጥ',
    'common.all': 'ሁሉም',
    'common.none': 'ምንም',
    'common.yes': 'አዎ',
    'common.no': 'አይ',
    'common.ok': 'እሺ',
    'common.apply': 'ተግብር',
    'common.update': 'አዘምን',
    'common.create': 'ፍጠር',
    'common.remove': 'አስወግድ',
    'common.duplicate': 'ደግም',
    'common.copy': 'ቅዳ',
    'common.paste': 'ለጥፍ',
    'common.cut': 'ቁረጥ',
    'common.undo': 'ተመለስ',
    'common.redo': 'እንደገና አድርግ',
    'common.region': 'ክልል',
    'common.select_region': 'ክልል ምረጥ',
    'common.role': 'ሚና',

    // Navigation
    'nav.dashboard': 'ዳሽቦርድ',
    'nav.complaints': 'ቅሬታዎች',
    'nav.new_complaint': 'አዲስ ቅሬታ',
    'nav.complaint_list': 'የቅሬታ ዝርዝር',
    'nav.search_complaints': 'ቅሬታዎችን ፈልግ',
    'nav.analytics': 'ትንታኔ',
    'nav.reports': 'ሪፖርቶች',
    'nav.users': 'የተጠቃሚ አስተዳደር',
    'nav.notifications': 'ማሳወቂያዎች',
    'nav.settings': 'ቅንብሮች',
    'nav.permissions': 'ፈቃዶች',
    'nav.logout': 'ውጣ',
    'nav.profile': 'መገለጫ',
    'nav.help': 'እርዳታ',
    'nav.about': 'ስለ',

    // Dashboard
    'dashboard.title': 'ዳሽቦርድ',
    'dashboard.welcome': 'እንኳን ደህና መጡ',
    'dashboard.overview': 'የሲስተም አጠቃላይ እይታ',
    'dashboard.total_complaints': 'ጠቅላላ ቅሬታዎች',
    'dashboard.open_complaints': 'ክፍት ቅሬታዎች',
    'dashboard.resolved_complaints': 'የተፈቱ ቅሬታዎች',
    'dashboard.pending_complaints': 'በመጠባበቅ ላይ ያሉ ቅሬታዎች',
    'dashboard.recent_complaints': 'የቅርብ ጊዜ ቅሬታዎች',
    'dashboard.quick_actions': 'ፈጣን እርምጃዎች',
    'dashboard.performance_metrics': 'የአፈጻጸም መለኪያዎች',
    'dashboard.activity_feed': 'የእንቅስቃሴ ዜና',
    'dashboard.system_status': 'የሲስተም ሁኔታ',
    'dashboard.online': 'በመስመር ላይ',
    'dashboard.offline': 'ከመስመር ውጭ',
    'dashboard.last_updated': 'በመጨረሻ የተዘመነ',
    'dashboard.view_all': 'ሁሉንም ተመልከት',
    'dashboard.no_data': 'ምንም መረጃ የለም',

    // Status
    'status.open': 'ክፍት',
    'status.in_progress': 'በሂደት ላይ',
    'status.pending': 'በመጠባበቅ ላይ',
    'status.resolved': 'ተፈትቷል',
    'status.escalated': 'ወደ ላይ ተላልፏል',
    'status.closed': 'ተዘግቷል',
    'status.cancelled': 'ተሰርዟል',
    'status.active': 'ንቁ',
    'status.inactive': 'ንቁ ያልሆነ',
    'status.enabled': 'ነቅቷል',
    'status.disabled': 'ተሰናክሏል',

    // Priority
    'priority.low': 'ዝቅተኛ',
    'priority.medium': 'መካከለኛ',
    'priority.high': 'ከፍተኛ',
    'priority.critical': 'ወሳኝ',
    'priority.urgent': 'አስቸኳይ',

    // የኢትዮጵያ ኤሌክትሪክ አገልግሎት የቅሬታ ዓይነቶች
    'complaint_type.pole-fall': 'የምሰሶ መውደቅ (አስቸኳይ)',
    'complaint_type.wire-cut': 'የሽቦ መቆራረጥ/መሰበር',
    'complaint_type.wire-sag': 'የሽቦ መዘንበል',
    'complaint_type.no-supply-total': 'ኃይል የለም - ጠቅላላ አካባቢ',
    'complaint_type.no-supply-partial': 'ኃይል የለም - ከፊል አካባቢ',
    'complaint_type.no-supply-single-house': 'ኃይል የለም - አንድ ቤት',
    'complaint_type.transformer-issue': 'የትራንስፎርመር ችግር',
    'complaint_type.breaker-problem': 'የብሬከር ችግር',
    'complaint_type.over-voltage': 'ከፍተኛ ቮልቴጅ',
    'complaint_type.under-voltage': 'ዝቅተኛ ቮልቴጅ',
    'complaint_type.voltage-fluctuation': 'የቮልቴጅ መለዋወጥ',
    'complaint_type.prepaid-meter-issue': 'የቅድመ ክፍያ ሜትር ችግር',
    'complaint_type.postpaid-meter-malfunction': 'የድህረ ክፍያ ሜትር ብልሽት',
    'complaint_type.meter-reading-issue': 'የሜትር ንባብ ችግር',
    'complaint_type.billing-issue': 'የክፍያ ችግር',
    'complaint_type.new-connection-request': 'አዲስ ግንኙነት ጥያቄ',
    'complaint_type.disconnection-request': 'መቋረጥ ጥያቄ',
    'complaint_type.reconnection-request': 'እንደገና መገናኘት ጥያቄ',
    'complaint_type.line-maintenance': 'የመስመር ጥገና ያስፈልጋል',
    'complaint_type.safety-concern': 'የደህንነት ጉዳይ',
    'complaint_type.other': 'ሌላ ችግር',

    // Regions
    'region.addis_ababa': 'አዲስ አበባ',
    'region.addis ababa': 'አዲስ አበባ',
    'region.afar': 'አፋር',
    'region.amhara': 'አማራ',
    'region.benishangul_gumuz': 'ቤንሻንጉል ጉሙዝ',
    'region.benishangul-gumuz': 'ቤንሻንጉል ጉሙዝ',
    'region.dire_dawa': 'ድሬዳዋ',
    'region.dire dawa': 'ድሬዳዋ',
    'region.gambela': 'ጋምቤላ',
    'region.harari': 'ሐረሪ',
    'region.oromia': 'ኦሮሚያ',
    'region.sidama': 'ሲዳማ',
    'region.snnpr': 'ደቡብ ብሔሮች ብሔረሰቦች እና ህዝቦች',
    'region.snnp': 'ደቡብ ብሔሮች',
    'region.somali': 'ሶማሊ',
    'region.tigray': 'ትግራይ',

    // Roles
    'role.admin': 'አስተዳዳሪ',
    'role.manager': 'ሥራ አስኪያጅ',
    'role.foreman': 'ሹም',
    'role.call_attendant': 'የጥሪ ተቀባይ',
    'role.technician': 'ቴክኒሻን',
    'role.supervisor': 'ተቆጣጣሪ',
    'role.operator': 'ኦፕሬተር',

    // Login
    'login.title': 'የኢትዮጵያ ኤሌክትሪክ አገልግሎት',
    'login.subtitle': 'የቅሬታ ማስተዳደሪያ ስርዓት',
    'login.email': 'የኢሜይል አድራሻ',
    'login.password': 'የይለፍ ቃል',
    'login.signin': 'ግባ',
    'login.signing_in': 'በመግባት ላይ...',
    'login.demo_credentials': 'የምሳሌ መለያዎች:',
    'login.click_to_fill': 'ቅጹን በራስ-ሰር ለመሙላት ማንኛውንም መለያ ጠቅ ያድርጉ',
    'login.success': 'መግባት ተሳክቷል',
    'login.success_desc': 'ወደ የኢትዮጵያ ኤሌክትሪክ አገልግሎት የቅሬታ ማስተዳደሪያ ስርዓት እንኳን በደህና መጡ',
    'login.error': 'መግባት አልተሳካም',
    'login.error_desc': 'እባክዎ የኢሜይል አድራሻዎን እና የይለፍ ቃልዎን ያረጋግጡ',
    'login.change_password': 'የይለፍ ቃል ቀይር',
    'login.change_password_desc': 'የይለፍ ቃልዎን ለመቀየር እባክዎ የስርዓት አስተዳዳሪዎን ያነጋግሩ',

    // Complaint Form
    'complaint.new_complaint': 'አዲስ ቅሬታ',
    'complaint.customer_name': 'የደንበኛ ስም',
    'complaint.customer_phone': 'የደንበኛ ስልክ',
    'complaint.customer_email': 'የደንበኛ ኢሜይል',
    'complaint.complaint_type': 'የቅሬታ ዓይነት',
    'complaint.priority': 'ቅድሚያ',
    'complaint.region': 'ክልል',
    'complaint.description': 'መግለጫ',
    'complaint.submit_complaint': 'ቅሬታ አስገባ',
    'complaint.submitting': 'በማስገባት ላይ...',
    'complaint.complaint_id': 'የቅሬታ መለያ',
    'complaint.date_created': 'የተፈጠረበት ቀን',
    'complaint.last_updated': 'በመጨረሻ የተዘመነ',
    'complaint.assigned_to': 'የተመደበለት',
    'complaint.customer_info': 'የደንበኛ መረጃ',
    'complaint.complaint_details': 'የቅሬታ ዝርዝሮች',
    'complaint.attachments': 'አባሪዎች',
    'complaint.comments': 'አስተያየቶች',
    'complaint.history': 'ታሪክ',
    'complaint.resolution': 'መፍትሄ',
    'complaint.feedback': 'ግብረመልስ',
    'complaint.rating': 'ደረጃ',
    'complaint.follow_up': 'ክትትል',
    'complaint.escalate': 'አሳድግ',
    'complaint.reassign': 'እንደገና መድብ',
    'complaint.close': 'ቅሬታ ዝጋ',
    'complaint.reopen': 'እንደገና ክፈት',
    'complaint.duplicate': 'እንደ ተደጋጋሚ ምልክት አድርግ',
    'complaint.merge': 'ቅሬታዎችን አዋህድ',
    'complaint.print': 'ቅሬታ አትም',
    'complaint.export': 'ቅሬታ ወደ ውጭ ላክ',
    'complaint.share': 'ቅሬታ አጋራ',
    'complaint.success': 'ቅሬታ በተሳካ ሁኔታ ተላከ',
    'complaint.created': 'ተፈጥሯል',
    'complaint.customer_address': 'የደንበኛ አድራሻ',
    'complaint.meter_number': 'የሜትር ቁጥር',
    'complaint.account_number': 'የመለያ ቁጥር',
    'complaint.title': 'የቅሬታ ርዕስ',
    'complaint.submit_new_complaint': 'አዲስ የኤሌክትሪክ አቅርቦት ቅሬታ አስገባ',
    'complaint.details': 'የቅሬታ ዝርዝሮች',
    'complaint.select_category': 'የቅሬታ ዓይነት ምረጥ',
    'complaint.select_priority': 'የቅድሚያ ደረጃ ምረጥ',
    'complaint.description_placeholder': 'ችግሩ የተጀመረበትን ጊዜ፣ የተጎዱ አካባቢዎችን እና ማንኛውንም ተዛማጅ መረጃን ጨምሮ የችግሩን ዝርዝር መግለጫ ያቅርቡ...',
    'common.submitting': 'በመላክ ላይ...',
    'complaint.updated': 'ቅሬታ ተዘምኗል',
    'complaint.update_success': 'ቅሬታው በተሳካ ሁኔታ ተዘምኗል።',
    'complaint.update_failed': 'ቅሬታን ማዘመን አልተሳካም',
    'complaint.fill_required_fields': 'እባክዎ ሁሉንም አስፈላጊ መስኮች ይሙሉ',
    'complaint.submission_success': 'ቅሬታ በተሳካ ሁኔታ ተላክ። የማጣቀሻ መለያ:',
    'complaint.submission_failed': 'ቅሬታ መላክ አልተሳካም',
    'complaint.success_desc': 'ቅሬታዎ በተሳካ ሁኔታ ተላክቷል',
    'complaint.error': 'የማስገባት ስህተት',
    'complaint.error_desc': 'ቅሬታዎን በማስገባት ላይ ስህተት ተፈጥሯል',

    // Form Labels and Placeholders
    'form.customer_information': 'የደንበኛ መረጃ',
    'form.complaint_details': 'የቅሬታ ዝርዝሮች',
    'form.enter_full_name': 'ሙሉ ስም ያስገቡ',
    'form.email': 'ኢሜይል',
    'form.phone_number': 'ስልክ ቁጥር',
    'form.address': 'አድራሻ',
    'form.complete_address': 'ንዑስ ከተማ/ወረዳን ጨምሮ ሙሉ አድራሻ',
    'form.select_region': 'ክልል ምረጥ',
    'form.service_center': 'የአገልግሎት ማዕከል',
    'form.select_service_center': 'የአገልግሎት ማዕከል ይምረጡ',
    'form.select_region_first': 'መጀመሪያ ክልል ይምረጡ',
    'form.complaint_number': 'የቅሬታ ቁጥር',
    'form.account_number': 'የመለያ ቁጥር',
    'form.complaint_title': 'የቅሬታ ርዕስ',
    'form.category': 'ዓይነት',
    'form.priority': 'ቅድሚያ',
    'form.detailed_description': 'ዝርዝር መግለጫ',
    'form.select_predefined_title': 'ቀድሞ የተዘጋጀ ርዕስ ምረጥ ወይም \'ብጁ\' ይምረጡ',
    'form.custom_title': 'ብጁ ርዕስ (የራስዎን ይተይቡ)',
    'form.enter_custom_title': 'የራስዎን ብጁ የቅሬታ ርዕስ ያስገቡ',
    'form.brief_description': 'የችግሩ አጭር መግለጫ',
    'form.select_complaint_category': 'የቅሬታ ዓይነት ምረጥ',
    'form.select_priority_level': 'የቅድሚያ ደረጃ ምረጥ',
    'form.submit_complaint': 'ቅሬታ አስገባ',
    'form.submitting': 'በማስገባት ላይ...',

    // Priority Labels
    'priority.emergency_response': 'የአስቸኳይ ጊዜ ምላሽ',
    'priority.high_priority': 'ከፍተኛ ቅድሚያ',
    'priority.standard_priority': 'መደበኛ ቅድሚያ',
    'priority.low_priority': 'ዝቅተኛ ቅድሚያ',

    // Emergency Info
    'emergency.hotline': 'የአስቸኳይ ጊዜ ስልክ:',
    'emergency.phone': '+251-11-EMERGENCY',
    'utility.portal_name': 'የኢትዮጵያ ኤሌክትሪክ አገልግሎት መግቢያ',

    // Customer Portal
    'customer_portal.title': 'የደንበኛ መግቢያ',
    'customer_portal.account_validation': 'የመለያ ማረጋገጫ',
    'customer_portal.enter_account_info': 'የመለያ መረጃዎን ያስገቡ',
    'customer_portal.account_info_desc': 'የቅሬታ ቅጽ ለመድረስ እባክዎ የኮንትራት መለያ ቁጥርዎን ወይም የንግድ አጋር ቁጥርዎን ያስገቡ።',
    'customer_portal.account_number_label': 'የኮንትራት መለያ / የንግድ አጋር ቁጥር',
    'customer_portal.account_number_placeholder': 'የመለያ ቁጥርዎን ያስገቡ (ለምሳሌ፣ 1000123456)',
    'customer_portal.account_number_help': 'ይህንን ቁጥር በኤሌክትሪክ ሂሳብዎ ወይም በኮንትራት ሰነዶችዎ ላይ ማግኘት ይችላሉ',
    'customer_portal.validate_account': 'መለያ አረጋግጥ',
    'customer_portal.validating': 'በማረጋገጥ ላይ...',
    'customer_portal.validation_success': 'መለያ ተረጋግጧል',
    'customer_portal.account_found': 'መለያዎ ተገኝቶ ተረጋግጧል።',
    'customer_portal.validation_failed': 'መለያ አልተገኘም',
    'customer_portal.validation_error': 'የማረጋገጫ ስህተት',
    'customer_portal.validation_error_desc': 'መለያን ማረጋገጥ አልተቻለም። እባክዎ እንደገና ይሞክሩ።',
    'customer_portal.account_verified': 'መለያ ተረጋግጧል',
    'customer_portal.customer_name': 'የደንበኛ ስም',
    'customer_portal.account_number': 'የመለያ ቁጥር',
    'customer_portal.account_type': 'የመለያ ዓይነት',

    // Complaint List
    'complaint_list.title': 'የቅሬታ ዝርዝር',
    'complaint_list.all_complaints': 'ሁሉም ቅሬታዎች',
    'complaint_list.my_complaints': 'የእኔ ቅሬታዎች',
    'complaint_list.assigned_complaints': 'የተመደቡ ቅሬታዎች',
    'complaint_list.unassigned': 'ያልተመደቡ',
    'complaint_list.overdue': 'ጊዜያቸው ያለፈ',
    'complaint_list.recent': 'የቅርብ ጊዜ',
    'complaint_list.filter_by': 'በ ማጣሪያ',
    'complaint_list.sort_by': 'በ ደርድር',
    'complaint_list.date_range': 'የቀን ክልል',
    'complaint_list.from_date': 'ከ ቀን',
    'complaint_list.to_date': 'እስከ ቀን',
    'complaint_list.results_found': 'ውጤቶች ተገኝተዋል',
    'complaint_list.no_complaints': 'ምንም ቅሬታዎች አልተገኙም',
    'complaint_list.load_more': 'ተጨማሪ ጫን',
    'complaint_list.refresh': 'ዝርዝሩን አድስ',
    'complaint_list.bulk_actions': 'የጅምላ እርምጃዎች',
    'complaint_list.select_all': 'ሁሉንም ምረጥ',
    'complaint_list.selected_items': 'የተመረጡ ንጥሎች',

    // Analytics & Reports
    'analytics.title': 'ትንታኔ',
    'analytics.overview': 'የትንታኔ አጠቃላይ እይታ',
    'analytics.complaints_by_type': 'በዓይነት ቅሬታዎች',
    'analytics.complaints_by_region': 'በክልል ቅሬታዎች',
    'analytics.complaints_by_status': 'በሁኔታ ቅሬታዎች',
    'analytics.complaints_by_priority': 'በቅድሚያ ቅሬታዎች',
    'analytics.resolution_time': 'አማካይ የመፍትሄ ጊዜ',
    'analytics.customer_satisfaction': 'የደንበኛ እርካታ',
    'analytics.performance_metrics': 'የአፈጻጸም መለኪያዎች',
    'analytics.trends': 'አዝማሚያዎች',
    'analytics.monthly_report': 'ወርሃዊ ሪፖርት',
    'analytics.quarterly_report': 'ሩብ ዓመታዊ ሪፖርት',
    'analytics.annual_report': 'ዓመታዊ ሪፖርት',
    'analytics.custom_report': 'ብጁ ሪፖርት',
    'analytics.generate_report': 'ሪፖርት ፍጠር',
    'analytics.export_data': 'መረጃ ወደ ውጭ ላክ',
    'analytics.chart_type': 'የቻርት ዓይነት',
    'analytics.time_period': 'የጊዜ ክፍል',
    'analytics.comparison': 'ንጽጽር',

    // Reports
    'reports.title': 'ሪፖርቶች',
    'reports.complaint_summary': 'የቅሬታ ማጠቃለያ',
    'reports.performance_report': 'የአፈጻጸም ሪፖርት',
    'reports.user_activity': 'የተጠቃሚ እንቅስቃሴ ሪፖርት',
    'reports.system_usage': 'የሲስተም አጠቃቀም ሪፖርት',
    'reports.customer_feedback': 'የደንበኛ ግብረመልስ ሪፖርት',
    'reports.sla_compliance': 'የSLA ተገዢነት ሪፖርት',
    'reports.regional_analysis': 'የክልላዊ ትንተና',
    'reports.trend_analysis': 'የአዝማሚያ ትንተና',
    'reports.executive_summary': 'የአስፈጻሚ ማጠቃለያ',
    'reports.detailed_report': 'ዝርዝር ሪፖርት',
    'reports.schedule_report': 'ሪፖርት መርሐግብር',
    'reports.email_report': 'ኢሜይል ሪፖርት',
    'reports.report_settings': 'የሪፖርት ቅንብሮች',

    // User Management
    'users.title': 'የተጠቃሚ አስተዳደር',
    'users.add_user': 'አዲስ ተጠቃሚ አክል',
    'users.full_name': 'ሙሉ ስም',
    'users.email_address': 'የኢሜይል አድራሻ',
    'users.phone_number': 'የስልክ ቁጥር',
    'users.role': 'ሚና',
    'users.service_center': 'የአገልግሎት ማዕከል',
    'users.active': 'ንቁ',
    'users.inactive': 'ንቁ ያልሆነ',
    'users.created': 'የተፈጠረ',

    // Settings
    'settings.title': 'የሲስተም ቅንብሮች',
    'settings.notifications': 'ማሳወቂያዎች',
    'settings.security': 'ደህንነት እና መዳረሻ',
    'settings.system': 'የሲስተም ውቅረት',
    'settings.language': 'ቋንቋ',
    'settings.save_changes': 'ለውጦችን አስቀምጥ',
    'settings.company_info': 'የድርጅት መረጃ',
    'settings.company_name': 'የድርጅት ስም',
    'settings.support_email': 'የድጋፍ ኢሜይል',
    'settings.support_phone': 'የድጋፍ ስልክ',
    'settings.website': 'ድረ-ገጽ',
    'settings.address': 'አድራሻ',
    'settings.timezone': 'የሰዓት ዞን',
    'settings.currency': 'ምንዛሪ',
    'settings.system_language': 'የሲስተም ቋንቋ',
    'settings.language_preview': 'የአሁኑ ቋንቋ ቅድመ እይታ',
    'settings.working_hours': 'የስራ ሰዓታት',
    'settings.start_time': 'የመጀመሪያ ሰዓት',
    'settings.end_time': 'የመጨረሻ ሰዓት',
    'settings.working_days': 'የስራ ቀናት',

    // Permissions
    'permissions.access_denied': 'ይህንን ሀብት ለመድረስ ፈቃድ የለዎትም',

    // Dashboard Titles
    'dashboard.admin_title': 'የሲስተም አስተዳደር ዳሽቦርድ',
    'dashboard.manager_title': 'የክልላዊ አስተዳደር ዳሽቦርድ',

    'dashboard.foreman_title': 'የመስክ ስራዎች ዳሽቦርድ',
    'dashboard.call_attendant_title': 'የደንበኛ አገልግሎት ዳሽቦርድ',
    'dashboard.technician_title': 'የቴክኒሻን ዳሽቦርድ',

    // Role Display Names
    'role.admin_display': 'አስተዳዳሪ',
    'role.manager_display': 'ሥራ አስኪያጅ',
    'role.foreman_display': 'ሹም',
    'role.call_attendant_display': 'የጥሪ ተቀባይ',
    'role.technician_display': 'ቴክኒሻን',

    // Search & Filter
    'search.title': 'ቅሬታዎችን ፈልግ',
    'search.subtitle': 'የላቀ ፍለጋ ተግባራትን በመጠቀም ቅሬታዎችን ያግኙ እና ያጣሩ',
    'search.placeholder': 'ቅሬታዎችን በርዕስ፣ መግለጫ ወይም መለያ ፈልግ...',
    'search.search_filter': 'ፍለጋ እና ማጣሪያ',
    'search.filters': 'ማጣሪያዎች',
    'search.export_results': 'ውጤቶችን ወደ ውጭ ላክ',
    'search.grid_view': 'የፍርግሞገጽ እይታ',
    'search.list_view': 'የዝርዝር እይታ',
    'search.all_status': 'ሁሉም ሁኔታዎች',
    'search.all_priorities': 'ሁሉም ቅድሚያዎች',
    'search.all_categories': 'ሁሉም ዓይነቶች',
    'search.all_regions': 'ሁሉም ክልሎች',
    'search.status': 'ሁኔታ',
    'search.priority': 'ቅድሚያ',
    'search.category': 'ዓይነት',
    'search.region': 'ክልል',

    // Customer Portal
    'customer.portal_title': 'የደንበኛ አገልግሎት መግቢያ',
    'customer.portal_subtitle': 'ቅሬታዎችን ያስገቡ እና የአገልግሎት ጥያቄዎችን የሁኔታ ይከታተሉ',
    'customer.search_title': 'መለያዎን ያግኙ',
    'customer.search_type': 'የፍለጋ ዓይነት',
    'customer.contract_account': 'የኮንትራት መለያ',
    'customer.business_partner': 'ንግድ አጋር',
    'customer.contract_number': 'የኮንትራት መለያ ቁጥር',
    'customer.business_partner_number': 'የንግድ አጋር ቁጥር',
    'customer.enter_search_value': 'የፍለጋ እሴት ያስገቡ',
    'customer.found': 'ደንበኛ ተገኝቷል',
    'customer.found_description': 'የደንበኛ መረጃ በተሳካ ሁኔታ ተጫናል',
    'customer.search_failed': 'ደንበኛ አልተገኘም። እባክዎ የመለያ ቁጥርዎን ያረጋግጡ።',
    'customer.information': 'የደንበኛ መረጃ',
    'customer.name': 'የደንበኛ ስም',
    'customer.phone': 'ስልክ ቁጥር',
    'customer.email': 'ኢሜይል አድራሻ',
    'customer.address': 'አድራሻ',
    'customer.meter_number': 'የሜትር ቁጥር',
    'customer.connection_type': 'የግንኙነት ዓይነት',
    'customer.file_complaint': 'ቅሬታ ያስገቡ',
    'customer.complaint_form': 'የቅሬታ ቅጽ',
    'customer.complaint_title_placeholder': 'የችግሩ አጭር መግለጫ',
    'customer.complaint_description_placeholder': 'ችግሩ ስለምን እንደሆነ ዝርዝር መረጃ ያቅርቡ፣ መጀመሪያ ጊዜ፣ የተጎዱ አካባቢዎች እና ማንኛውንም ተዛማጅ መረጃን ጨምሮ...',
    'customer.urgency': 'የአስቸኳይነት ደረጃ',
    'customer.urgency.low': 'ዝቅተኛ - ሊጠብቅ ይችላል',
    'customer.urgency.medium': 'መካከለኛ - መደበኛ ቅድሚያ',
    'customer.urgency.high': 'ከፍተኛ - አስቸኳይ ትኩረት ያስፈልጋል',
    'customer.preferred_contact': 'የሚመረጠው የመገናኘት መሣሪያ',
    'customer.contact.phone': 'ስልክ ጥሪ',
    'customer.contact.email': 'ኢሜይል',
    'customer.contact.sms': 'SMS',
    'customer.additional_phone': 'ተጨማሪ ስልክ (አማራጭ)',
    'customer.additional_email': 'ተጨማሪ ኢሜይል (አማራጭ)',
    'customer.complaint_notice': 'ቅሬታዎ የሚገለፀበት እና ተገቢ ቡድን የሚመደበበት ነው። በሚመረጡት የመገናኘት መሣሪያ ላይ ዝማኔዎችን ያገኛሉ።',
    'customer.status.active': 'ንቁ',
    'customer.status.inactive': 'ንቁ ያልሆነ',
    'customer.status.suspended': 'ተሰማራ',

    // Landing Page
    'landing.welcome_title': 'ወደ ኢትዮጵያ ኤሌክትሪክ አገልግሎት እንኳን ደህና መጡ',
    'landing.welcome_description': 'በኢትዮጵያ ለሁሉም ክልሎች አስተማማኝ የኤሌክትሪክ አገልግሎት አስተማማኝ አጋርነታችን። ቅሬታዎችን ያስገቡ፣ የአገልግሎት ጥያቄዎችን ይከታተሉ እና የደንበኛ ድጋፍን ያግኙ።',
    'landing.customer_portal': 'የደንበኛ መግቢያ',
    'landing.customer_portal_description': 'ቅሬታዎችን በመስመር ላይ ያስገቡ እና የአገልግሎት ጥያቄዎችን ይከታተሉ።',
    'landing.staff_portal': 'የሰራተኛ መግቢያ',
    'landing.staff_portal_description': 'የኢትዮጵያ ኤሌክትሪክ አገልግሎት ሰራተኞች ለማስተዳደሪያ ስርዓት መድረሻ።',
    'landing.access_customer_portal': 'የደንበኛ መግቢያ ያግኙ',
    'landing.staff_login': 'የሰራተኛ መግባት',
    'landing.contact_title': 'እርዳታ ያስፈልጋል?',
    'landing.contact_description': 'የደንበኛ አገልግሎት ቡድናችን ለመርዳት እዚህ ነው።',
    'landing.contact.phone': 'ስልክ ድጋፍ',
    'landing.contact.email': 'ኢሜይል ድጋፍ',
    'landing.contact.hours': 'የአገልግሎት ሰዓታት',
    'landing.contact.weekdays': 'ሰኞ-እሁድ: 8:00 እለት - 6:00 ምሽት',
    'landing.contact.weekend': 'ቅዳሜ: 9:00 እለት - 1:00 ምሽት',
    'landing.footer.rights': 'ሁሉም መብቶች የተያዙ ናቸው።',
    'landing.footer.version': 'ስሪት',
    'landing.feature.file_complaints': 'ቅሬታዎችን በመስመር ላይ ያስገቡ',
    'landing.feature.track_status': 'የቅሬታ ሁኔታ ይከታተሉ',
    'landing.feature.account_lookup': 'የመለያ መረጃ ፍለጋ',
    'landing.feature.multilingual': 'በእንግሊዝኛ እና በአማርኛ ይገኛል',
    'landing.feature.manage_complaints': 'የደንበኛ ቅሬታዎችን ያስተዳድሩ',
    'landing.feature.analytics_reports': 'ትንታኔ እና ሪፖርቶች',
    'landing.feature.user_management': 'የተጠቃሚ አስተዳደር',
    'landing.feature.role_permissions': 'በሚና ላይ የተመሠረተ ፈቃዶች',
  },
};

const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageProvider;
